### ISSUE TITLE
#TK26 Modificar estilos de tarjetas de profesionales en web

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [workflix/workflix-full#40]

**Comment by BraianTroncoso** [comment]
Sugerencia de como realizar la tarea.
-Encontrar stylos viejos en donde se mostraban las cards
-Copiar y pegar los stylos en el siguiente html(Adaptando el bucle for para recorrerlo correctamente).

![Captura de pantalla_2024-04-26_14-37-21](https://github.com/workflix/workflix-full/assets/95662710/a97af0cd-f054-41fd-9ba8-35957c751b6f)

Tambien podrian dar los stylos que quieran siguiendo la paleta de colores actual, en caso de usar boostrap, recordar incluirlo en el index.
